### ISSUE TITLE
3 Hazelhatch stations exist in allstations.json

### ISSUE THREAD

**Issue by IrishTnT** [IrishTnT/Ironroad#5]
`{
        "StationAlias": "Celbridge (Hazelhatch ) ",
        "StationCode": "HZLCH",
        "StationDesc": "Hazelhatch",
        "StationId": "78",
        "StationLatitude": "53.3223",
        "StationLongitude": "-6.52356"
    },
    {
        "StationAlias": "Celbridge (Hazelhatch ) ",
        "StationCode": "HAZEF",
        "StationDesc": "Hazelhatch",
        "StationId": "978",
        "StationLatitude": "53.3223",
        "StationLongitude": "-6.52356"
    },
    {
        "StationAlias": "Celbridge (Hazelhatch ) ",
        "StationCode": "HAZES",
        "StationDesc": "Hazelhatch",
        "StationId": "1078",
        "StationLatitude": "53.3223",
        "StationLongitude": "-6.52356"
    },
`

**Comment by IrishTnT** [comment]
It might be best to force it into the checking statement if its any of these stations, and if so, ignore the triplepost.

**Comment by IrishTnT** [comment]
Accidental closure.

**Comment by IrishTnT** [comment]
Being solved in 0.2.5

**Comment by IrishTnT** [comment]
Hijacking issue for all related errors and issues related to solving this.

`Traceback (most recent call last):
  File "c:\Ironroad\Ironroad\Ironroad.py", line 402, in <module>
    stationSearch()
  File "c:\Ironroad\Ironroad\Ironroad.py", line 176, in stationSearch
    nameCheck = next((iterdata))
StopIteration`

^ Solve by catching before that.

**Comment by IrishTnT** [comment]
Solved in 0.2.5 stable.
